# Exported from Render on 2025-09-03T10:14:48Z
services:
- type: web
  name: ours-backend
  runtime: node
  repo: https://github.com/allentrev/ours
  plan: free
  envVars:
  - key: CLERK_WEBHOOK_SECRET
    sync: false
  - key: CLERK_PUBLISHABLE_KEY
    sync: false
  - key: CLERK_SECRET_KEY
    sync: false   
  - key: PORT
    sync: false
  - key: CLIENT_URL
    sync: false
  - key: NODE_ENV
    sync: false
  - key: MONGO_URI
    sync: false
  - key: POSTMAN1
    sync: false
  - key: IK_URL_ENDPOINT
    sync: false
  - key: IK_PRIVATE_KEY
    sync: false
  - key: IK_PUBLIC_KEY
    sync: false
  - key: MJ_APIKEY_PUBLIC
    sync: false
  - key: MJ_APIKEY_PRIVATE
    sync: false
  - key: SMTP_HOST
    sync: false
  - key: SMTP_PORT
    sync: false
  - key: SMTP_SECURE
    sync: false
  - key: SMTP_USER
    sync: false
  - key: SMTP_PASS
    sync: false
  - key: SMTP_FROM
    sync: false
  - key: SMTP_TO
    sync: false  
  region: singapore
  buildCommand: npm install && npm run render-build
  startCommand: npm start
  healthCheckPath: /health
  autoDeployTrigger: commit
  rootDir: ./backend
- type: web
  name: ours-frontend
  runtime: static
  repo: https://github.com/allentrev/ours
  envVars:
  - key: VITE_IK_URL_ENDPOINT
    sync: false
  - key: VITE_IK_PUBLIC_KEY
    sync: false
  - key: VITE_CLERK_PUBLISHABLE_KEY
    sync: false
  - key: VITE_API_URL
    sync: false
  buildCommand: npm run build
  staticPublishPath: dist
  autoDeployTrigger: commit
  rootDir: ./client
version: "1"
